main: com.gabezter4.hotel_manager.main.hotel_time
name: Hotel Manager
version: 0.1.0

commands:
  hotel:
    description: Main Command
    usage: /hotel
    permission: hm.main
    permission-message: You are not allowed to do this command.
  hotelkick:
    description: Main Command
    usage: /hotelkick
    permission: hm.main
    permission-message: You are not allowed to do this command.
  hotelcheckin:
    description: Main Command
    usage: /hotelcheckin
    permission: hm.checkin
    permission-message: You are not allowed to do this command.
  hotelcheckout:
    description: Main Command
    usage: /hotel checkout 
    permission: hm.checkout
    permission-message: You are not allowed to do this command.
  hotelset:
    description: Main Command
    usage: /hotelset
    permission: hm.set
    permission-message: You are not allowed to do this command.
  hotelcreate:
    description: Main Command
    usage: /hotelcreate 
    permission: hm.create
    permission-message: You are not allowed to do this command.
  hotelgenerate:
    description: Main Command
    usage: /hotelgenerate
    permission: hm.generate
    permission-message: You are not allowed to do this command.
  hotelconfig:
    description: Main Command
    usage: /hotelconfig
    permission: hm.config
    permission-message: You are not allowed to do this command.
permissions:
  hm.main:
    default: op
  hm.kick:
    default: op
  hm.checkin:
    default: op
  hm.checkout:
    default: op
  hm.checkin:
    default: op
  hm.create:
    default: op
  hm.generate:
    default: op
  hm.config:
    default: op