main: com.gabezter4.hotel_manager.main.hotel_time
name: Hotel Manager
version: 0.1.0

Commands:
  hotel:
    description: Main Command
    usage: /hotel 
    permission: hm.main
    permission-message: You are not allowed to do this command.
